### ISSUE TITLE
Hubinterface in command

### ISSUE THREAD

**Issue by rickerd** [symfony/mercure#104]
I've got a command that relies on the HubInterface from mercure.
Luckily I can use this in dev mode but when going to production the HubInterface is gone and not injectable.

I have no clue why this cannot be done since it does work in dev mode.

services.yaml
```    App\Command\PlannedLotteryDrawsCommand:
        class: App\Command\PlannedLotteryDrawsCommand
        arguments: [ '@lottery.subscriberhelper', '@service_container', '@mercure.hub.default.traceable.inner' ]
        tags:
            - { name: console.command }
```

PlannedLotteryCommand.php
``` public function __construct(LotterySubscriberHelper $lotterySubscriberHelper, ContainerInterface $container, HubInterface $hub)
    {
        parent::__construct();
        $this->lotterySubscriberHelper = $lotterySubscriberHelper;
        $this->container = $container;
        $this->hub = $hub;
    }
```

**Comment by dunglas** [comment]
The `mercure.hub.default.traceable.inner` is an internal debug service, only available in dev.

Use `mercure.hub.default` instead, or, better, rely on autowiring.

**Comment by rickerd** [comment]
I used this; @Symfony\Component\Mercure\HubInterface
