### ISSUE TITLE
Error after symfony fresh install

### ISSUE THREAD

**Issue by gponty** [symfony/mercure#17]
Hi,

I have an error message when i install symfony/mercure after a Symfony fresh install :

symfony new --full testMercure
composer require mercure

Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.3.*"
Package operations: 2 installs, 0 updates, 0 removals
  - Installing symfony/mercure (v0.2.0): Loading from cache
  - Installing symfony/mercure-bundle (v0.1.2): Loading from cache
Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
Symfony operations: 1 recipe (6267b0d44223790bc621777fd0038c8b)
  - Configuring symfony/mercure-bundle (>=0.1): From github.com/symfony/recipes:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In MercureExtension.php line 52:
!!                                           
!!    Notice: Undefined index: jwt_provider  
!!                                           
!!  
!!  
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json to its original content.

Any idea ?
Thank you

**Comment by dunglas** [comment]
This will be fixed by symfony/recipes#672. In the meantime you can install Mercure with `composer req mercure --no-scripts` then fix `config/packages/mercure.yaml` by hand (remove the `enable_profiler` line).

**Comment by dunglas** [comment]
Fixed
