### ISSUE TITLE
how can I get my active subscribers?

### ISSUE THREAD

**Issue by mahsamnz** [symfony/mercure#26]

**Comment by dunglas** [comment]
You can use the [subscription API](https://mercure.rocks/spec#subscription-api) to do that. You need to pass the `subscriptions` config option of the hub to `1` to enable this API. Then you can use Symfony HTTP client to request it.

It could be nice to an helper method in this component to request this API.

**Comment by mahsamnz** [comment]
Thank you for your response .

**Comment by asobaleu** [comment]
hello
mb somedoby can help me?
i try to get all subscriptions via subscription API
but i always get HTTP/1.1 401 Unauthorized returned for "http://mercure/.well-known/mercure/subscriptions"

my code

$this->httpClient->request('GET', $_ENV['MERCURE_PUBLISH_URL'] . '/subscriptions', [
            'headers' => [
                'Authorization' => 'Bearer ' . $_ENV['MERCURE_JWT_TOKEN'],
                'Content-Type' => 'application/ld+json',
            ]
        ])->getContent();
