### ISSUE TITLE
Are detached execution or deamon available ?

### ISSUE THREAD

**Issue by gabrielrosset** [symfony/mercure#28]
Bonjour,
L’exécution de la commande mercure ne rends pas la main.
Je ne trouve pas de directive dans la doc qui permette de nativement exécuter en mode détaché ou ‘daemon’ le binaire.
Existe-t-il une solution native dans mercure pour gérer une exécution détaché ? ou doit-on développer une surcouche system au binaire, avec les mécanismes standards de stop/star etc. ?

**Comment by dunglas** [comment]
Bonjour Gabriel,

Effectivement le binaire n'est pas conçu pour rendre la main. En production il est recommandé d'utiliser un outil tel que `supervisor` ou `systemd` pour monitorer le process et éventuellement le relancer en cas de problème. Voici un exemple avec supervisor: https://mercure.rocks/docs/hub/cookbooks#monitoring-the-hub-using-supervisor

Il est également possible d'utiliser les commandes standards telles que `nohup` et `screen` mais `supervisor` reste conseillé.

Une troisième alternative est d'utiliser les images Docker que nous fournissons avec un orchestrateur tel Kubernetes ou Swarm. Nous fournissons un Chart pour Kubernetes: https://hub.helm.sh/charts/stable/mercure

Cordialement,

**Comment by gabrielrosset** [comment]
Bonjour Kevin, 
Merci pour cette réponse rapide et pour les liens.
