### ISSUE TITLE
Release supporting PHP 8

### ISSUE THREAD

**Issue by acelaya** [symfony/mercure#32]
Hey.

I see there is a merged PR which brings PHP 8 support to the library. Is there plans to publish a new `symfony/mercure` release which includes that?

I'm asking because I'm not completely sure how the release process works for this kind of components. Is it expected to have a new release when Symfony 5.2 is released, or is it completely detached?

**Comment by chalasr** [comment]
The release cycle is not the same as the symfony/symfony one, we release from time to time (feature-based).
Stay tuned, it will happen in the next days.

**Comment by acelaya** [comment]
Cool, thanks for the information :)
