### ISSUE TITLE
 Signed tags can’t be verified

### ISSUE THREAD

**Issue by DavidPrevot** [symfony/mercure#34]
Hi,

I’m unable to retrieve the GPG key BD07D52C38D3139F8CAA6C3F9D0C5D6EEB42C445 from dunglas@gmail.com (doesn’t seem to be available on any keyserver, nor via WKD). Can you please point me to the public key in order to verify those tags, and hopefully make it publicly (more?) available?

Regards

David

BD07D52C38D3139F8CAA6C3F9D0C5D6EEB42C445

**Comment by chalasr** [comment]
@dunglas up to fix this? `gpg --send-key 9D0C5D6EEB42C445`

**Comment by dunglas** [comment]
Done.
