### ISSUE TITLE
Why throwing an exception ?

### ISSUE THREAD

**Issue by Soonz** [symfony/mercure#4]
In case the server crashed, it would be nice to know if it happened and refresh the page like that : 

```php
public function broadcast()
{
	$update = new Update( $this->hub, $this->data );
	if( $this->publisher->__invoke( $update ) !== false ) {
		return true;
	}
	return false;
}
```

If "false" is returned, I can refresh the page in Javascript by sending some JSON from the controller : 

```php
if( !$mercure->broadcast() ) {
	return new JsonResponse( ['streamSucceeded' => false ] );
}
```

```js
.done( function( data ) {
if( data.streamSucceeded === false ) {
    location.reload( true );
    return;
}
```

https://github.com/symfony/mercure/blob/ba133bfb3d20419235e858c3524030e1b548a9de/src/Publisher.php#L98

**Comment by Soonz** [comment]
If only one user for some reason can't connect to the hub it will reload the page of every users connected to this hub. Not a good idea.

**Comment by azjezz** [comment]
Exceptions give you more details about the issue and what went wrong, you can still use `try { } catch() {}` to achieve your end goal :smile:  

```php
    public function broadcast(): bool {
      $publisher = $this->publisher;
      $update = new Update($this->hub, $this->data);
      try {
        $publisher($update);
      } catch(\Throwable $e) {
        // log exception here

        return false;
      }

      return true;
    }
```

**Comment by Soonz** [comment]
Yeah, you're right, that's what I tried at first but I couldn't make it work.

I'm closing the issue, thanks.
