### ISSUE TITLE
Remove same domain restriction

### ISSUE THREAD

**Issue by micru** [symfony/mercure#54]
What is the reason for restricting Mercure Authentication to the same (Sub-)Domain?

Our Api runs at `api.mydomain.tld` and Mercure at `mercure.mydomain.tld` 

This check makes it impossible for us to get authorization working https://github.com/symfony/mercure/blob/main/src/Authorization.php#L97

Can it be removed or do have any security concerns?
If not i suggest removing this check or make it at least configurable

**Comment by dunglas** [comment]
It's not enforced by Mercure but by the browsers directly (it's part of CORS). This check is just here to improve the Developer Experience by throwing a descriptive error (browser errors related to this are cryptic), but this will not work even without this check.

It's just not possible to share cookies between two different domains. If you really want to do this, you need to use the `Authorization` header (which is also supported by Mercure).

**Comment by micru** [comment]
I'm sorry to disagree with you and maybe I have expressed myself in a misleading way, but it is possible to set a cookie for all subdomains of the same domain. For this you have to set the "domain" parameter in the cookie. 

https://www.php.net/manual/en/function.session-set-cookie-params.php

So I think it is technically possible to run our applications on different subdomains of the same domain like i mentionend we intent to have 2 subdomains for api and mercure, e.g. `api.mydomain.tld` and `mercure.mydomain.tld`

**Comment by dunglas** [comment]
Ok got it, I misunderstood your first comment. Indeed this works and it's a bug. The goal of this check is to prevent setting a cookie for another domain. We must adapt the check to allow this use case. I'll try to fix this as soon as I can (PR welcome in the meantime!). cc @azjezz

**Comment by azjezz** [comment]
the solution is to get the second level domain + top level domain here instead of using the current host.

https://github.com/symfony/mercure/blob/52b074d0c9bc303605bcd053563a8c67ed9ca55a/src/Authorization.php#L91

by 

```php
$host = strtolower($request->getHost());
$hostSegments  = array_reverse(explode('.', $currentDomain));
              //  | - SLD 
             //   |                   | - LTD
             //   |                   |
             //   v                   v
$currentDomain = $hostSegments[1].'.'.$hostSegments[0];
```

**Comment by dunglas** [comment]
@azjezz this will not work in some cases (`.co.uk`, `.github.io`, `.asso.fr`...) but I think that it's good enough. The solution to handle all possible cases is to use the Public Suffix List but it looks overkill to me. WDYT?

**Comment by micru** [comment]
To me the solution of @azjezz  would be perfectly good.
