### ISSUE TITLE
no_proxy is ignored

### ISSUE THREAD

**Issue by partikule** [symfony/mercure#63]
** Issue **

**Even the` .env` var `no_proxy` is set, it will be ignore by the Publisher.**

**Our environment :**
- Docker container with "php" service and "mercure" service defined in on docker-compose.yml
- PHP 7.4 with curl lib installed
- Use of CurlHttpClient by the Publisher
- IP proxy needed for external requests
- no_proxy set to http://mercure 
 - Production environment, use of Tinyproxy

**Caddyfile :** 

```
{
    # Debug mode (disable it in production!)
    debug
    # HTTP/3 support
    # experimental_http3
}
:80
log

route {
    redir / /.well-known/mercure/ui/
    encode gzip
    mercure {
        heartbeat_interval 30s
        publisher_jwt {$MERCURE_JWT_KEY}
        subscriber_jwt {$MERCURE_JWT_KEY}
        # Server's IP address
        cors_origins {$MERCURE_CORS_DOMAIN}
        # Enable the demo endpoint (disable it in production!)
        demo
        ui
    }
    respond "Not Found" 404
}
```

Our App/Publisher (src/Middleware/Mercure/Publisher.php) : 

````
<?php


namespace App\Middleware\Mercure;

use \Exception;
use Psr\Log\LoggerAwareTrait;
use Psr\Log\LoggerInterface;
use Symfony\Component\Mercure\PublisherInterface;
use Symfony\Component\Mercure\Update;
use Symfony\Component\Serializer\SerializerInterface;

class Publisher
{
	use LoggerAwareTrait;

	private $serializer;
	private $publisher;

	public function __construct(
		PublisherInterface $publisher,
		SerializerInterface $serializer,
		LoggerInterface $logger
	)
	{
		$this->serializer = $serializer;
		$this->publisher = $publisher;
		$this->setLogger($logger);
	}

	/**
	 * Usage of IRI for topics required (can be false url)
	 * https://tools.ietf.org/html/rfc3987
	 *
	 * @param array|string $topics
	 * @param array $data
	 * @param bool $private
	 * @return Update
	 */
	public function createPublication($topics, array $data = [], bool $private = true): Update
	{
		$dataJson = $this->serializer->serialize($data, 'json');

		return new Update($topics, $dataJson, $private);
	}

	/**
	 * @param Update $update
	 * @return Exception
	 */
	public function publish(Update $update): ?Exception
	{
		// mode can be sync, or async (RabbitMQ, Kafka...)
		if (getenv('MERCURE_PUSH_MODE') === 'publisher')
			try {
				$publisher = $this->publisher;
				$publisher($update);
			} catch (Exception $e) {
				return $e;
			}

		return null;
	}
}
````

**Comment by partikule** [comment]
**Possible solution :** 

Do not define vendor/symfony/mercure/src/Publisher.php as final, so then _invoke method could be extended.

**Comment by dunglas** [comment]
Can't you just configure the HttpClient instance properly?

**Comment by azjezz** [comment]
This not an issue in symfony/mercure, as the library doesn't take anything from .env into account.

What you want is to configure the http client property as @dunglas has mentioned.

e.g:
```php
use Symfony\Component\HttpClient\HttpClient;
use Symfony\Component\Mercure;

$client = HttpClient::create([
  'proxy' => $myProxy,
  // a comma separated list of hosts that do not require a proxy to be reached
  'no_proxy' => 'mercure.example.com',
]);

$hub = new Mercure\Hub('https://mercure.example.com', $provider, $factory, $public_url, $client);


$hub->publish(...);
```

---

> Do not define vendor/symfony/mercure/src/Publisher.php as final, so then _invoke method could be extended.

The `Publisher` is deprecated, you should use `Hub` instead, but either way, you shouldn't extend either, both `Publisher` and `Hub` have a corresponding interface ( `PublisherInterface` and `HubInterface` ).

You should instead implement that interface, and type hint against the interface in your code ( this will also allow you to use [`MockHub`](https://github.com/symfony/mercure/blob/main/src/MockHub.php) in your test )
