### ISSUE TITLE
Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by JulienSellier** [symfony/mercure#66]
Hello there,

I'm trying to deploy my project on a "preproduction" environment and I got this error when publishing on Mercure Hub:

`Peer certificate cannot be authenticated with given CA certificates for https://xxx`

It's a "preproduction" environment so it's not important but we can't pass "verify_peer" option to HttpClient using the hub.

Can we add this option ? Should I open a PR ?

Thanks

**Comment by zspine** [comment]
I had the similar problem and solved it by changing the Caddyfile and using http in the local setup instead of https. (not the best solution but it works)

```
{
    auto_https disable_redirects
    # Debug
    {$DEBUG}
    # HTTP/3 support
    servers {
        protocol {
            experimental_http3
        }
    }
}
```

**Comment by JulienSellier** [comment]
> I had the similar problem and solved it by changing the Caddyfile and using http in the local setup instead of https. (not the best solution but it works)
> 
> ```
> {
>     auto_https disable_redirects
>     # Debug
>     {$DEBUG}
>     # HTTP/3 support
>     servers {
>         protocol {
>             experimental_http3
>         }
>     }
> }
> ```

Thanks it's good to know but I have no access (or not easy access) to my "preproduction" server ; on my local setup I have no issue with the ssl certificate...

It's why I try to solve this problem on the code side.

I tried to extends or decorates but the Hub is final.... :/

**Comment by JulienSellier** [comment]
I found the solution, we can change HTTPClient's defaults values for "verify_peer" and "verify_host" for a specific environnement:

framework.yaml
```yaml
framework:
    http_client:
        default_options:
            verify_host: false
            verify_peer: false
```
