### ISSUE TITLE
Cannot inject HubInterface

### ISSUE THREAD

**Issue by rickerd** [symfony/mercure#79]
Hi,

I cannot DI the HubInterface into a symfony command.
The services.yaml doesn't show it has a injectable hub interface and throws an error in prod.
However switching the envirionment to dev doesn't show any errors...

I'm clueless on where to search.
I've included the symfony mercure bundle + mercure itself. In bundles.php only symfony/mercure is loaded with the "all" option.

No seperate files in the dev or prod directories whatsoever.

When switching to prod it gives me an error as following;
```
Argument 1 passed to App\Command\PlannedLotteryDrawsCommand::__construct() must be an instance of Symfony\Component\Mercure\HubInterface, string given, called in /private/tmp/cache/prod/ContainerDbqeB3N/getPlannedLotteryDrawsCommandService.php on line 9
```

![image](https://user-images.githubusercontent.com/1032429/146831684-5dc04d3b-6457-42c1-9c74-b2ede98650f1.png)

**Comment by chalasr** [comment]
please consider explaining how you solved this if you don't mind, so that anyone facing the same issue can find it and save some time

**Comment by chalasr** [comment]
Got it, I’m sorry for this.
